### ISSUE TITLE
[Enhancement]: Drawing outside of the window

### ISSUE THREAD

**Issue by vi** [LinwoodDev/Butterfly#521]
### What happened?

It thinks that input device keeps touching and interprets further clicks as double touches.

[bottombug.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/23edcfe9-2ac5-4d04-aac1-b82918321a51)

### Version

2.0.0-beta.14

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Seems like the pointer up event doesn't fire if you go out of the window and release the input device.
I will investigate how I can fix this

**Comment by CodeDoctorDE** [comment]
I tested it myself but couldn't replicate it anymore.
Which browser do you use on which operating system?

**Comment by vi** [comment]
Firefox 115.3.0esr on Linux Debian with i3 on Xorg, with a number of extensions installed and `user-chrome.css` snippets active.

Trying on a clean Firefox profile: the bug is reproducible.
Trying on a clean Chromium profile: not reproducible.

**Comment by CodeDoctorDE** [comment]
Yeah, chromium works fine on me.
The problem is that I don't get a PointerUp event if the window is unfocused: https://dartpad.dev/?id=21592fa42e503eb99da3cabd804c18fb
I currently see no solution how to fix it.

**Comment by CodeDoctorDE** [comment]
Fixed in 2.0.0-beta.15, if you refresh the website, it should be fixed

**Comment by vi** [comment]
Still reproducible on https://preview.butterfly.linwood.dev/ . Settings show 15'th revision.

**Comment by CodeDoctorDE** [comment]
Oh, I will look at it again...

**Comment by CodeDoctorDE** [comment]
Okay, it should now reset all inputs when unfocused. Can you test if the bug appears in the current version? (don't forget to refresh the site after loading so that it can fetch the newest version)

**Comment by vi** [comment]
Behaviour changed now: it does not lock to zoom mode. Stroke being drawn gets frozen until I click again, it cancels the stroke entirely.

[disappear.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/f6e71b2d-5f83-4541-b487-2eedb113f895)


Better than before (I can continue using the app instead of being forced to reload the window and maybe lose unsaved content), but still suboptimal. User should not "be afraid of the edges". Not sure how to attain it though. Maybe some heuristics?

**Comment by CodeDoctorDE** [comment]
Oh you are right. Thanks for testing

**Comment by CodeDoctorDE** [comment]
I think now it should be fixed

**Comment by vi** [comment]
Now it does not erase the stroke, but also does not continue after cursor is offscreen.

It should work like in e.g. https://sketch.io/sketchpad/ - in the same Firefox I can continue drawing a stroke even when cursor is off the browser window. It also explicitly reacts to mouse button release even when cursor is away.

[sketchio.webm](https://github.com/LinwoodDev/Butterfly/assets/173219/eacd5e09-e09d-42b8-912c-bed58e88f0c0)
 
Can Butterfly work the same way?

**Comment by CodeDoctorDE** [comment]
The problem is I can't get the pointer id that leaves the app, and if you release the device when outside of the app, I don't get this event.
I think we can keep this for now. The bug is fixed.

**Comment by vi** [comment]
> if you release the device when outside of the app, I don't get this event

Why sketch.io does receive a mouse up event even when cursor is away from Firefox window, as demonstrated on the video?

> pointer id

If there is only one pointer (i.e. mouse, no multi-touch) then any mouse release is _the_ pointer release.

**Comment by CodeDoctorDE** [comment]
Okay...
I researched a bit and found out you need to capture the input. I will try it out now and notify you if I found a solution.

https://stackoverflow.com/questions/14407869/capture-mouseup-event-outside-of-browser-window

**Comment by CodeDoctorDE** [comment]
Okay I tried everything but couldn't find a solution. setPointerCapture(event.pointerId) does not work when listing on them.
I will mark this as https://github.com/LinwoodDev/Butterfly/labels/good%20first%20issue if anyone wants to help me fixing this.

**Comment by MrGumpIT** [comment]
What is the drawing area widget? Where is it located in the code? Could you try to identify its dimensions and deactivate the pen when it reaches there without having to read the id

**Comment by CodeDoctorDE** [comment]
Hi,
thanks for your interest.
The drawaing area widget is this: https://github.com/LinwoodDev/Butterfly/blob/4716732b6309c20dd654a3bb4846f17a72ed033b/app/lib/views/view.dart#L380.

I intentionally disabled this feature: https://github.com/LinwoodDev/Butterfly/blob/4716732b6309c20dd654a3bb4846f17a72ed033b/app/lib/views/view.dart#L375.
The problem is that I don't get a pointerup event to unregister the input and otherwise you will end up zooming with one input because the other input wasn't unregistered.

You can try it out if you remove the onExit callback and start the webserver with `flutter run -d web-server` and connect with firefox to this url

**Comment by MrGumpIT** [comment]
Can this work for you?

https://github.com/LinwoodDev/Butterfly/assets/47901429/2479137e-4c2e-4cec-a1fa-c8edd4d36b20

**Comment by CodeDoctorDE** [comment]
Fixed in 2.1.0-beta.4 thanks to @MrGumpIT in https://github.com/LinwoodDev/Butterfly/pull/646
